# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'CigarWarehouse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for CigarWarehouse
 

  pod 'SVProgressHUD'
  #pod 'AFNetworking'
  pod 'MyLayout'
  pod 'ZYCornerRadius'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'BRPickerView'
  pod 'FMDB/SQLCipher'
  pod 'SGQRCode'

  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'MBProgressHUD'
  pod 'SnapKit'
  pod 'ZipArchive'
  pod 'DeviceKit'
  pod 'YYImage'
  pod 'TagListView'
  pod 'DGCharts'

  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'IQKeyboardManager'
  pod 'SDCycleScrollView'
  

  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
      end
    end
  end


end
